'use client';
import { useEffect,useRef,useState } from 'react';
import { useRouter } from 'next/navigation';

function ymd(d:Date){const y=d.getFullYear();const m=String(d.getMonth()+1).padStart(2,'0');const day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`;}
function shiftDays(base:Date,days:number){const d=new Date(base);d.setDate(d.getDate()+days);return d;}
type Ws='seller'|'onboarding'|'customer_success'|'incentives';
function money(v:any){const n=Number(v||0);return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);}
function rupees(v:any){const n=Number(v||0);return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(n);}

export default function Analytics(){
 const router=useRouter(); const now=new Date(),today=ymd(now);
 const [user,setUser]=useState<any>(null),[workspace,setWorkspace]=useState<Ws>('seller'),[from,setFrom]=useState(today),[to,setTo]=useState(today),[data,setData]=useState<any>(null),[loading,setLoading]=useState(false);
 const lastLoadedUrl=useRef('');
 useEffect(()=>{(async()=>{const r=await fetch('/api/auth/access');if(!r.ok){router.replace('/login');return;}const u=(await r.json()).user;const sellerAdmin=u.isSuperAdmin||u.access?.seller==='admin';const onboardingAdmin=u.isSuperAdmin||u.access?.onboarding==='admin';const customerSuccessAccess=u.isSuperAdmin||u.access?.onboarding==='admin'||u.access?.onboarding==='customer_success';if(!sellerAdmin&&!onboardingAdmin&&!customerSuccessAccess){router.replace(u.access?.onboarding?'/onboarding':'/');return;}setUser(u);const q=typeof window!=='undefined'?new URLSearchParams(window.location.search).get('workspace'):null;const requested=q==='seller'||q==='onboarding'||q==='customer_success'||q==='incentives';const wanted:Ws=requested?q as Ws:'seller';const allowed=wanted==='seller'?sellerAdmin:wanted==='onboarding'?onboardingAdmin:wanted==='incentives'?Boolean(u.isSuperAdmin):customerSuccessAccess;const initial:Ws=allowed?wanted:sellerAdmin?'seller':onboardingAdmin?'onboarding':'customer_success';setWorkspace(initial);await load(initial,today,today);})();},[]);
 async function load(ws:Ws,f:string,t:string){setWorkspace(ws);setFrom(f);setTo(t);setLoading(true);setData(null);const url=ws==='seller'?`/api/analytics/daily?from=${f}&to=${t}`:ws==='incentives'?`/api/incentives?from=${f}&to=${t}`:ws==='onboarding'?`/api/onboarding/analytics?from=${f}&to=${t}`:`/api/customer-success/analytics?from=${f}&to=${t}`;lastLoadedUrl.current=url;const r=await fetch(url,{cache:'no-store'});if(r.ok)setData(await r.json());setLoading(false);}
 async function refreshLoadedOperational(){const url=lastLoadedUrl.current;if(!url.startsWith('/api/onboarding/analytics?')&&!url.startsWith('/api/customer-success/analytics?'))return;const r=await fetch(url,{cache:'no-store'});if(r.ok)setData(await r.json());}
 useEffect(()=>{if(workspace==='seller')return;const refresh=()=>{if(document.visibilityState==='visible')void refreshLoadedOperational();};window.addEventListener('focus',refresh);const timer=window.setInterval(refresh,30000);return()=>{window.removeEventListener('focus',refresh);window.clearInterval(timer);};},[workspace]);
 function preset(kind:'today'|'yesterday'|'7d'|'month'|'lastMonth'){const current=new Date();if(kind==='month')return load(workspace,ymd(new Date(current.getFullYear(),current.getMonth(),1)),ymd(current));if(kind==='lastMonth')return load(workspace,ymd(new Date(current.getFullYear(),current.getMonth()-1,1)),ymd(new Date(current.getFullYear(),current.getMonth(),0)));if(kind==='today')return load(workspace,ymd(current),ymd(current));if(kind==='yesterday'){const d=shiftDays(current,-1);return load(workspace,ymd(d),ymd(d));}return load(workspace,ymd(shiftDays(current,-6)),ymd(current));}
 if(!user)return <div className="center">Loading…</div>;
 const sellerAdmin=user.isSuperAdmin||user.access?.seller==='admin',onboardingAdmin=user.isSuperAdmin||user.access?.onboarding==='admin',customerSuccessAccess=user.isSuperAdmin||user.access?.onboarding==='admin'||user.access?.onboarding==='customer_success';
 return <div className="app-shell"><header><div><strong>Pi Commerce</strong><span> · Analytics</span></div><div className="header-actions">{(user.isSuperAdmin||user.access?.seller)&&<a href="/">Seller Workspace</a>}{(user.isSuperAdmin||user.access?.onboarding)&&<a href="/onboarding">Onboarding Workspace</a>}{(user.isSuperAdmin||sellerAdmin||onboardingAdmin)&&<a href="/admin/access">Manage Access</a>}<span className="badge">{user.name}</span></div></header><main>
  {(Number(sellerAdmin)+Number(onboardingAdmin)+Number(customerSuccessAccess)>1)&&<section className="workspace-switch">{sellerAdmin&&<button className={workspace==='seller'?'active':''} onClick={()=>load('seller',from,to)}>Sellers</button>}{onboardingAdmin&&<button className={workspace==='onboarding'?'active':''} onClick={()=>load('onboarding',from,to)}>Onboarders</button>}{customerSuccessAccess&&<button className={workspace==='customer_success'?'active':''} onClick={()=>load('customer_success',from,to)}>Post-Live Customer Success</button>}{user.isSuperAdmin&&<button className={workspace==='incentives'?'active':''} onClick={()=>load('incentives',from,to)}>Incentives</button>}</section>}
  <section className="card"><div className="section-label">{workspace==='seller'?'Seller Analytics':workspace==='onboarding'?'Onboarding Analytics':workspace==='incentives'?'Incentives':'Post-Live Customer Success Analytics'}</div><div className="preset-row"><button onClick={()=>preset('today')}>Today</button><button onClick={()=>preset('yesterday')}>Yesterday</button><button onClick={()=>preset('7d')}>Last 7 Days</button>{workspace==='incentives'&&<><button onClick={()=>preset('month')}>This Month</button><button onClick={()=>preset('lastMonth')}>Last Month</button></>}</div><div className="range-row"><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="primary" onClick={()=>load(workspace,from,to)} disabled={loading}>{loading?'Loading…':'Apply'}</button>{workspace==='seller'&&<a className="primary" href={`/api/export/dispositions?from=${from}&to=${to}`}>Download Disposition CSV</a>}</div>
  {data&&workspace==='seller'&&<SellerSummary data={data}/>} {data&&workspace==='onboarding'&&<OnboardingSummary data={data}/>} {data&&workspace==='customer_success'&&<CustomerSuccessSummary data={data}/>} {data&&workspace==='incentives'&&<IncentiveSummary data={data}/>}</section>
  {data&&workspace==='incentives'&&<IncentiveDetail data={data}/>}
  {data&&workspace==='seller'&&<><div className="two-col"><section className="card"><div className="section-label">Fresh calls — disposition</div><Split rows={data.freshDispositionSplit}/></section><section className="card"><div className="section-label">Repeat calls — disposition</div><Split rows={data.repeatDispositionSplit}/></section></div><section className="card"><div className="section-label">Agent Performance</div><table className="split"><thead><tr><th>Agent</th><th>Attempts</th><th>Unique</th><th>Connected</th><th>Connect %</th><th>Interested</th><th>Callbacks</th><th>Payments</th><th>Revenue</th><th>Payment Issues</th><th>Tech Issues</th><th>WA</th></tr></thead><tbody>{data.agentPerformance.map((r:any)=><tr key={r.name}><td>{r.name}</td><td>{r.attempts}</td><td>{r.unique}</td><td>{r.connected}</td><td>{r.connectRate}%</td><td>{r.interested}</td><td>{r.callbacks}</td><td>{r.paymentDone}</td><td>{money(r.revenue)}</td><td>{r.paymentIssues}</td><td>{r.technicalIssues}</td><td>{r.whatsappHandoffs}</td></tr>)}</tbody></table></section><section className="card"><div className="section-label">Team Revenue</div>{data.teamPerformance?.length?<table className="split"><thead><tr><th>Team (Team Lead)</th><th>Sellers with sales</th><th>Payments</th><th>Revenue</th></tr></thead><tbody>{data.teamPerformance.map((t:any)=><tr key={t.team}><td>{t.team}</td><td>{t.members.join(', ')}</td><td>{t.paymentDone}</td><td>{money(t.revenue)}</td></tr>)}</tbody></table>:<div className="empty">No team sales for this period.</div>}<div className="note">A team is its Team Lead plus the BDEs reporting to them on the sale date. SBDEs are not part of a team.</div></section></>}
  {data&&workspace==='onboarding'&&<section className="card"><div className="section-label">Onboarder Performance</div><table className="split"><thead><tr><th>Onboarder</th><th>Assigned</th><th>Open (As on)</th><th>Touches</th><th>Ads Live</th><th>Subs Renewed</th><th>Top-up</th><th>Tech Open (As on)</th><th>Tech Resolved</th><th>Avg TAT</th></tr></thead><tbody>{data.agentPerformance.map((r:any)=><tr key={r.id}><td>{r.name}</td><td>{r.assigned}</td><td>{r.open}</td><td>{r.touches}</td><td>{r.ads_live}</td><td>{r.subscriptions_renewed}</td><td>{money(r.top_up_amount)}</td><td>{r.tech_open}</td><td>{r.tech_resolved}</td><td>{r.avg_tat??'—'}</td></tr>)}</tbody></table></section>}
  {data&&workspace==='customer_success'&&<section className="card"><div className="section-label">Customer Success Performance</div><table className="split"><thead><tr><th>Person</th><th>Touches</th><th>Customers</th><th>Callbacks</th><th>Another Ad Live</th><th>Creative Updated</th><th>Subs Renewed</th><th>Top-ups</th><th>Top-up Value</th><th>Not Interested</th><th>Refund</th></tr></thead><tbody>{data.agentPerformance.map((r:any)=><tr key={r.id}><td>{r.name}</td><td>{r.touches}</td><td>{r.customers_touched}</td><td>{r.callbacks_scheduled}</td><td>{r.another_ads_live}</td><td>{r.creatives_updated}</td><td>{r.subscriptions_renewed}</td><td>{r.top_up_count}</td><td>{money(r.top_up_amount)}</td><td>{r.not_interested}</td><td>{r.refund_requested}</td></tr>)}</tbody></table></section>}
 </main></div>;
}
function SellerSummary({data}:{data:any}){return <><div className="kpis analytics-kpis"><K n={data.totalAttempts} l="Total Calls"/><K n={data.uniqueAttempted} l="Unique Customers"/><K n={data.connected} l="Connected"/><K n={data.notConnected} l="Not Connected"/><K n={data.connectRateKnownDenominator==null?'—':data.connectRateKnownDenominator+'%'} l="Connect Rate"/><K n={data.interested} l="Interested"/><K n={data.callbackRequested} l="Callbacks"/><K n={data.paymentDone} l="Payment Done"/><K n={money(data.revenue)} l="Revenue (ex-GST)"/><K n={data.paymentIssues} l="Payment Issues"/><K n={data.technicalIssues} l="Technical Issues"/><K n={data.whatsappHandoffs} l="WhatsApp Handoffs"/><K n={data.fbLinkingIssues} l="FB Linking Issues"/><K n={data.visitsRequested} l="Visits Requested"/><K n={data.freshCustomers} l="Fresh Calls"/><K n={data.repeatCustomers} l="Repeat Calls"/></div><div className="note">Seller Quick Answers uses seller dispositions as before. The only onboarding exception is explicit Subscription Renewed, which adds one Payment Done for the onboarder who renewed it.</div></>}
function OnboardingSummary({data}:{data:any}){return <div className="kpis analytics-kpis"><K n={data.cases_received} l="Cases Received"/><K n={data.open_cases} l="Open Cases (As on)"/><K n={data.touches} l="Touches"/><K n={data.connected} l="Connected"/><K n={data.callbacks_scheduled} l="Callbacks Scheduled"/><K n={data.in_process} l="In Process"/><K n={data.ads_live} l="Ads Live"/><K n={data.external_ads_live} l="Ads Made Live Externally"/><K n={`${data.ads_live_rate}%`} l="Ads Live Rate (As on)"/><K n={data.subscriptions_renewed} l="Subs Renewed"/><K n={money(data.top_up_amount)} l="Top-up Done"/><K n={data.technical_open} l="Tech Open (As on)"/><K n={data.technical_resolved} l="Tech Resolved"/><K n={data.not_interested} l="Not Interested"/><K n={data.refund_requested} l="Refund Requested"/><K n={data.avg_days_to_live??'—'} l="Avg Days to Live"/><K n={data.ageing_open_cases} l="Ageing Open Cases (As on)"/><K n={data.ageing_cases_touched} l="Ageing Cases Touched"/><K n={data.ageing_cases_closed} l="Ageing Cases Closed"/></div>}
function CustomerSuccessSummary({data}:{data:any}){return <div className="kpis analytics-kpis"><K n={data.touches} l="Post-Live Touches"/><K n={data.customers_touched} l="Customers Touched"/><K n={data.callbacks_scheduled} l="Callbacks Scheduled"/><K n={data.in_process} l="In Process"/><K n={data.meetings_aligned} l="Meetings Aligned"/><K n={data.technical_issues} l="Technical Issues"/><K n={data.another_ads_live} l="Another Ad Made Live"/><K n={data.creatives_updated} l="Creative Updated"/><K n={data.subscriptions_renewed} l="Subs Renewed"/><K n={data.top_up_count} l="Top-ups"/><K n={money(data.top_up_amount)} l="Top-up Value"/><K n={data.not_interested} l="Not Interested"/><K n={data.refund_requested} l="Refund Requested"/></div>}
function IncentiveSummary({data}:{data:any}){const t=data.totals||{};const tiles:[any,string][]=[[rupees(t.payout),'Total Incentive'],[rupees(t.sellerDaily),'Seller Daily (to 30 Sep)'],[rupees(t.weeklyBonus),'Seller Weekly Bonus (to 30 Sep)'],[rupees(t.revenuePay),'Seller Revenue Incentive'],[money(t.revenue),'Seller Revenue (weeks paid)'],[rupees(t.casePay),'Case Incentive'],[rupees(t.topUpPay),'Top-up Incentive'],[rupees(t.renewalPay),'Renewal Incentive'],[t.sales,'Sales Counted'],[t.adsLiveCases,'Ads Live Cases'],[money(t.topUpValue),'Top-up Value'],[money(t.renewalValue),'Renewal Value']];return <><div className="kpis analytics-kpis">{tiles.map(([n,l])=><K key={l} n={n} l={l}/>)}</div><div className="note">Up to 30 Sep 2026 sellers were paid a daily incentive on sales plus a weekly bonus. From 1 Oct 2026 they are paid weekly (Mon–Sun, first week 1–4 Oct) on ex-GST revenue: cumulative BDE / SBDE / TL slabs, and a TL also earns half of each BDE's payout. A weekly payout is counted on the Sunday its week ends. Onboarders and CSMs: Ads Live cases daily; each top-up and, from 1 Oct, each Subscription Renewed is priced on its own (under ₹1,000 nothing, up to ₹5,000 5%, above 10%). A renewal before Ads Live goes to the case owner, after Ads Live to whoever logged it.</div></>}
const personCols:[string,string,(r:any)=>any][]=[['sales','Sales',r=>r.sales],['sellerDaily','Seller Daily',r=>rupees(r.sellerDaily)],['weeklyBonus','Weekly Bonus',r=>rupees(r.weeklyBonus)],['revenue','Revenue',r=>money(r.revenue)],['revenuePay','Revenue Slabs',r=>rupees(r.revenuePay)],['teamShare','TL Team Share',r=>rupees(r.teamShare)],['adsLiveCases','Ads Live Cases',r=>r.adsLiveCases],['casePay','Case Incentive',r=>rupees(r.casePay)],['topUpValue','Top-up Value',r=>money(r.topUpValue)],['topUpPay','Top-up Incentive',r=>rupees(r.topUpPay)],['renewalValue','Renewal Value',r=>money(r.renewalValue)],['renewalPay','Renewal Incentive',r=>rupees(r.renewalPay)]];
const roleName:any={BDE:'BDE',SBDE:'SBDE',TL:'Team Lead'};
function IncentiveDetail({data}:{data:any}){const p=data.plans||{};const people=data.people||[];const cols=personCols.filter(([k])=>people.some((r:any)=>Number(r[k]||0)!==0));const obRenewals=(data.onboarderDaily||[]).some((r:any)=>r.renewals>0);return <>
  <section className="card"><div className="section-label">Incentive by Person</div>{people.length?<table className="split"><thead><tr><th>Person</th>{cols.map(([k,l])=><th key={k}>{l}</th>)}<th>Total</th></tr></thead><tbody>{people.map((r:any)=><tr key={r.name}><td>{r.name}</td>{cols.map(([k,,f])=><td key={k}>{f(r)}</td>)}<td><b>{rupees(r.total)}</b></td></tr>)}</tbody></table>:<div className="empty">No incentive activity for this period.</div>}</section>
  {data.sellerRevenueWeekly?.length>0&&<section className="card"><div className="section-label">Seller Weekly Revenue Incentive</div><table className="split"><thead><tr><th>Week</th><th>Seller</th><th>Role</th><th>Team Lead</th><th>Days in role</th><th>Sales</th><th>Revenue</th><th>Slab Payout</th><th>TL Team Share</th><th>Total</th></tr></thead><tbody>{data.sellerRevenueWeekly.map((r:any)=><tr key={r.weekStart+r.person+r.role+(r.teamLead||'')}><td>{r.weekStart} – {r.weekEnd}</td><td>{r.person}</td><td>{roleName[r.role]||r.role}</td><td>{r.teamLead||'—'}</td><td>{r.activeFrom===r.weekStart&&r.activeTo===r.weekEnd?'Full week':`${r.activeFrom} – ${r.activeTo}`}</td><td>{r.sales}</td><td>{money(r.revenue)}</td><td>{rupees(r.slabPay)}</td><td>{rupees(r.teamShare)}</td><td>{rupees(r.pay)}</td></tr>)}</tbody></table><div className="note">Revenue counts sales dated on or after 1 Oct 2026. A role applies from the day it changes: sales count under the role held on the sale date, and each role in a week is priced on its own slabs.</div></section>}
  {(data.sellerDaily?.length>0||data.sellerWeekly?.length>0)&&<div className="two-col"><section className="card"><div className="section-label">Seller Daily Incentive (to 30 Sep)</div>{data.sellerDaily?.length?<table className="split"><thead><tr><th>Date</th><th>Seller</th><th>Plan</th><th>Sales</th><th>Incentive</th></tr></thead><tbody>{data.sellerDaily.map((r:any)=><tr key={r.date+r.person}><td>{r.date}</td><td>{r.person}</td><td>{r.plan}</td><td>{r.sales}</td><td>{rupees(r.pay)}</td></tr>)}</tbody></table>:<div className="empty">No seller sales for this period.</div>}</section>
  <section className="card"><div className="section-label">Seller Weekly Bonus (to 30 Sep)</div>{data.sellerWeekly?.length?<table className="split"><thead><tr><th>Week</th><th>Seller</th><th>Sales</th><th>Bonus</th></tr></thead><tbody>{data.sellerWeekly.map((r:any)=><tr key={r.weekStart+r.person}><td>{r.weekStart} – {r.weekEnd}</td><td>{r.person}</td><td>{r.sales}</td><td>{rupees(r.pay)}</td></tr>)}</tbody></table>:<div className="empty">No week ending in this period.</div>}</section></div>}
  <section className="card"><div className="section-label">Onboarder & CSM Daily Incentive</div>{data.onboarderDaily?.length?<table className="split"><thead><tr><th>Date</th><th>Person</th><th>Ads Live Cases</th><th>Case Incentive</th><th>Top-ups</th><th>Top-up Value</th><th>Top-up Incentive</th>{obRenewals&&<><th>Renewals</th><th>Renewal Value</th><th>Renewal Incentive</th></>}<th>Total</th></tr></thead><tbody>{data.onboarderDaily.map((r:any)=><tr key={r.date+r.person}><td>{r.date}</td><td>{r.person}</td><td>{r.cases}</td><td>{rupees(r.casePay)}</td><td>{r.topUps}</td><td>{money(r.topUpValue)}</td><td>{rupees(r.topUpPay)}</td>{obRenewals&&<><td>{r.renewals}</td><td>{money(r.renewalValue)}</td><td>{rupees(r.renewalPay)}</td></>}<td>{rupees(r.pay)}</td></tr>)}</tbody></table>:<div className="empty">No onboarder incentive activity for this period.</div>}</section>
  <section className="card"><div className="section-label">Plans in Force</div><table className="split"><thead><tr><th>Plan</th><th>Effective</th><th>Rule</th></tr></thead><tbody>
   {(p.sellerDaily||[]).map((x:any)=><tr key={'d'+x.from}><td>Seller daily · {x.name}</td><td>{x.from}{x.to?` – ${x.to}`:''}</td><td>{money(x.unlockPay)} on sale {x.unlock}; {x.bands.map((b:any,i:number)=>`${money(b.rate)} each ${i===0?`${x.unlock+1}–${b.upTo}`:b.upTo?`${x.bands[i-1].upTo+1}–${b.upTo}`:`${x.bands[i-1].upTo+1}+`}`).join('; ')}</td></tr>)}
   {(p.sellerWeekly||[]).map((x:any)=><tr key={'w'+x.from}><td>Seller weekly · {x.name}</td><td>{x.from}{x.to?` – ${x.to}`:''}</td><td>{x.slabs.map((s:any)=>`${money(s.pay)} at ${s.at}+ sales`).join('; ')} (Mon–Sun)</td></tr>)}
   {(p.sellerRevenue||[]).map((x:any)=><tr key={'r'+x.from}><td>Seller weekly · {x.name}</td><td>{x.from}{x.to?` – ${x.to}`:''}</td><td>{Object.entries(x.slabs).map(([role,sl]:any)=>`${roleName[role]}: ${sl.map((s:any)=>`${money(s.at)} → +${money(s.pay)}`).join(', ')}`).join(' · ')}; TL also earns {x.tlShareOfBde*100}% of each BDE's payout (Mon–Sun, ex-GST revenue)</td></tr>)}
   {(p.onboarder||[]).map((x:any)=><tr key={'o'+x.from}><td>Onboarder / CSM · {x.name}</td><td>{x.from}{x.to?` – ${x.to}`:''}</td><td>{money(x.unlockPay)} on case {x.unlock}, then {money(x.perCase)} each; each top-up{x.paysRenewals?' and each renewal':''} priced on its own: below {money(x.topUpMin)} earns nothing, up to {money(x.topUpCeiling)} earns {x.rateUpToCeiling*100}%, above {money(x.topUpCeiling)} earns {x.rateAboveCeiling*100}% of the whole amount</td></tr>)}
   {(p.saleCounting||[]).map((x:any)=><tr key={'s'+x.from}><td>Seller sale counting</td><td>{x.from}</td><td>{x.rule==='unique_per_day'?'A customer counts once per day':'A customer counts once, on their first Payment done'}</td></tr>)}
  </tbody></table><div className="note">Seller team from 1 Oct: {(()=>{const cur=new Map<string,any>();for(const r of (p.roles||[])) if(r.effectiveFrom<=data.to) cur.set(r.person,r);return [...cur.values()].filter((r:any)=>r.role!=='NONE').map((r:any)=>`${r.person} (${roleName[r.role]}${r.teamLead?` → ${r.teamLead}`:''})`).join(', ')||'none set';})()}. Onboarder / CSM roster: {(p.onboarderRoster||[]).map((m:any)=>m.to?`${m.name} (until ${m.to})`:m.name).join(', ')}.</div></section>
 </>}
function K({n,l}:{n:any,l:string}){return <div><b>{n}</b><span>{l}</span></div>}
function Split({rows}:{rows:any[]}){return rows.length?<table className="split"><thead><tr><th>Outcome</th><th>#</th><th>%</th></tr></thead><tbody>{rows.map(r=><tr key={r.outcome}><td>{r.outcome}</td><td>{r.count}</td><td>{r.percent}%</td></tr>)}</tbody></table>:<div className="empty">No calls for this period.</div>}
