'use client';
import { useEffect,useState } from 'react';
import { useRouter } from 'next/navigation';

const options=[['','No Access'],['agent','Agent'],['admin','Admin']];
export default function AccessPage(){
 const router=useRouter(); const [me,setMe]=useState<any>(null); const [agents,setAgents]=useState<any[]>([]); const [manage,setManage]=useState<any>(null); const [msg,setMsg]=useState('');
 const [name,setName]=useState(''),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[seller,setSeller]=useState(''),[onboarding,setOnboarding]=useState(''),[superAdmin,setSuperAdmin]=useState(false);
 async function load(){const r=await fetch('/api/admin/access',{cache:'no-store'});if(!r.ok)return;const j=await r.json();setAgents(j.agents||[]);setManage(j.manage);}
 useEffect(()=>{(async()=>{const r=await fetch('/api/auth/access');if(!r.ok){router.replace('/login');return;}const u=(await r.json()).user;setMe(u);await load();})();},[]);
 async function create(){setMsg('');const r=await fetch('/api/admin/access',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,username,password,sellerAccess:seller||null,onboardingAccess:onboarding||null,isSuperAdmin:superAdmin})});const j=await r.json();if(!r.ok){setMsg(j.error||'Could not create user');return;}setName('');setUsername('');setPassword('');setSeller('');setOnboarding('');setSuperAdmin(false);setMsg('User created.');await load();}
 async function patch(id:string,field:string,value:any){setMsg('');const r=await fetch('/api/admin/access',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,[field]:value})});const j=await r.json();if(!r.ok){setMsg(j.error||'Could not update access');return;}await load();}
 if(!me||!manage)return <div className="center">Loading…</div>;
 return <div className="app-shell"><header><div><strong>Pi Commerce</strong><span> · Access</span></div><div className="header-actions">{me.access?.seller&&<a href="/">Seller Workspace</a>}{me.access?.onboarding&&<a href="/onboarding">Onboarding Workspace</a>}<span className="badge">{me.name}</span></div></header><main>
 <section className="card"><div className="section-label">Create User</div><div className="form-grid"><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Username<input value={username} onChange={e=>setUsername(e.target.value.toLowerCase())}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{manage.seller&&<label>Seller Workspace<select value={seller} onChange={e=>setSeller(e.target.value)}>{options.map(([v,l])=><option value={v} key={l}>{l}</option>)}</select></label>}{manage.onboarding&&<label>Onboarding Workspace<select value={onboarding} onChange={e=>setOnboarding(e.target.value)}>{options.map(([v,l])=><option value={v} key={l}>{l}</option>)}</select></label>}{manage.global&&<label className="toggle-label"><span>Super Admin</span><input type="checkbox" checked={superAdmin} onChange={e=>setSuperAdmin(e.target.checked)}/></label>}</div><button className="primary" onClick={create} disabled={!name||!username||password.length<8}>Create User</button>{msg&&<div className="note">{msg}</div>}</section>
 <section className="card"><div className="section-label">Users & Workspace Access</div><div className="access-list">{agents.map(a=><div className="access-row" key={a.id}><div className="access-person"><b>{a.name}</b><span>{a.username} · {a.active?'Active':'Inactive'}</span></div>{manage.seller&&<label>Seller<select value={a.seller_access||''} onChange={e=>patch(a.id,'sellerAccess',e.target.value||null)}>{options.map(([v,l])=><option value={v} key={l}>{l}</option>)}</select></label>}{manage.onboarding&&<label>Onboarding<select value={a.onboarding_access||''} onChange={e=>patch(a.id,'onboardingAccess',e.target.value||null)}>{options.map(([v,l])=><option value={v} key={l}>{l}</option>)}</select></label>}{manage.global&&<label className="mini-check">Super Admin<input type="checkbox" checked={Boolean(a.is_super_admin)} onChange={e=>patch(a.id,'isSuperAdmin',e.target.checked)}/></label>}<button onClick={()=>patch(a.id,'active',!a.active)}>{a.active?'Deactivate':'Activate'}</button></div>)}</div></section>
 </main></div>;
}
