'use client';
import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';

type Node={id:string;code:string;label:string;level:number;parent_id:string|null;sort_order:number};

function fmtDate(v:any){ if(!v)return '—'; const d=new Date(String(v).slice(0,10)+'T00:00:00'); return d.toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'}); }
function outcome(c:any){return [c.l0_label_snapshot,c.l1_label_snapshot,c.l2_label_snapshot].filter(Boolean).join(' → ') || c.status_raw || c.remark || 'No outcome recorded';}

export default function AgentConsole(){
  const router=useRouter();
  const [agent,setAgent]=useState<any>(null); const [cid,setCid]=useState(''); const [data,setData]=useState<any>(null); const [loading,setLoading]=useState(false); const [nodes,setNodes]=useState<Node[]>([]); const [error,setError]=useState('');
  const [l0,setL0]=useState(''); const [l1,setL1]=useState(''); const [l2,setL2]=useState(''); const [remark,setRemark]=useState(''); const [fb,setFb]=useState(''); const [saving,setSaving]=useState(false);
  useEffect(()=>{(async()=>{const m=await fetch('/api/auth/me');if(!m.ok){router.replace('/login');return;}setAgent((await m.json()).agent);const d=await fetch('/api/dispositions');if(d.ok)setNodes((await d.json()).nodes);})();},[router]);
  const l0s=useMemo(()=>nodes.filter(n=>n.level===0),[nodes]); const l0node=nodes.find(n=>n.code===l0); const l1s=nodes.filter(n=>n.level===1&&n.parent_id===l0node?.id); const l1node=nodes.find(n=>n.code===l1); const l2s=nodes.filter(n=>n.level===2&&n.parent_id===l1node?.id); const fbRequired=['Payment done','Taken to WhatsApp for closure','Technical blocker'].includes(l1node?.label||''); const remarkRequired=['Callback — mid-pitch','Customer at counter','Asked for specific time','Driving / travelling','Owner not available'].includes(l1node?.label||'');
  async function fetchCustomer(){if(!cid.trim())return;setLoading(true);setError('');const r=await fetch('/api/customers/'+encodeURIComponent(cid.trim()));const j=await r.json();setLoading(false);if(!r.ok){setError(j.error||'Could not fetch');return;}setData(j);}
  async function submit(){if(!l0||!cid.trim())return;setSaving(true);setError('');const r=await fetch('/api/calls',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({customerId:cid.trim(),l0Code:l0,l1Code:l1||null,l2Code:l2||null,remark:remark||null,facebookPageStatus:fb||null})});const j=await r.json();setSaving(false);if(!r.ok){setError(j.error||'Could not log disposition');return;}setL0('');setL1('');setL2('');setRemark('');setFb('');await fetchCustomer();}
  async function logout(){await fetch('/api/auth/logout',{method:'POST'});router.replace('/login');}
  if(!agent)return <div className="center">Loading…</div>;
  const flags=data?.activeFlags||{};
  return <div className="app-shell"><header><div><strong>Pi Commerce</strong><span> · Disposition Platform</span></div><div className="header-actions">{agent.role==='admin'&&<><a href="/analytics">Analytics</a><a href="/admin/agents">Manage Agents</a></>}<span className="badge">{agent.name}</span><button className="linkbtn" onClick={logout}>Logout</button></div></header><main>
    <section className="card"><div className="section-label">1 · Customer ID</div><div className="search-row"><input value={cid} onChange={e=>setCid(e.target.value)} onKeyDown={e=>e.key==='Enter'&&fetchCustomer()} placeholder="Paste or type customer ID"/><button onClick={fetchCustomer} disabled={loading}>{loading?'Fetching…':'Fetch'}</button></div>{error&&<div className="error padtop">{error}</div>}</section>
    {data&&<><section className="card"><div className="section-label">2 · Customer Summary</div><div className="summary-grid"><div><span>Customer ID</span><b>{data.customer.customer_id}</b></div><div><span>Total attempts</span><b>{data.summary.totalAttempts}</b></div><div><span>First called</span><b>{fmtDate(data.summary.firstCallDate)}</b></div><div><span>Last called</span><b>{fmtDate(data.summary.lastCallDate)}</b></div><div><span>Last agent</span><b>{data.summary.lastAgent||'—'}</b></div><div><span>Latest outcome</span><b>{data.summary.latestOutcome}</b></div></div>
      {Object.values(flags).some(Boolean)&&<div className="flags"><span>Historical flags</span>{Object.entries(flags).filter(([,v])=>v).map(([k])=><em key={k}>{k.replace(/([A-Z])/g,' $1').replace(/^./,s=>s.toUpperCase())}</em>)}</div>}
    </section>
    <section className="card"><div className="section-label">3 · Complete History</div>{data.calls.length===0?<div className="empty"><strong>New Customer</strong><br/>No previous history for this ID.</div>:<div className="timeline">{data.calls.map((c:any)=><div className={'event '+(c.source_type==='legacy_followup'?'followup':'')} key={c.id}><div className="event-top"><div><b>{fmtDate(c.call_date)}</b> · {c.agent_name||c.agent_name_raw||'Unknown agent'}</div><span className="status">{outcome(c)}</span></div><div className="event-meta">Call {c.attempt_number}{c.is_legacy?' · Historical':' · New taxonomy'}{c.source_type==='legacy_followup'?' · Legacy follow-up':''}</div>{c.what_happened&&<div className="what">What happened: {c.what_happened}</div>}<div className={c.remark?'remark':'remark muted'}>{c.remark||'No remark logged'}</div></div>)}</div>}</section>
    <section className="card"><div className="section-label">4 · Log New Disposition</div><div className="form-grid"><label>L0 — Call Outcome<select value={l0} onChange={e=>{setL0(e.target.value);setL1('');setL2('')}}><option value="">Select outcome</option>{l0s.map(n=><option key={n.id} value={n.code}>{n.label}</option>)}</select></label>{l1s.length>0&&<label>L1 — Reason<select value={l1} onChange={e=>{setL1(e.target.value);setL2('')}}><option value="">Select</option>{l1s.map(n=><option key={n.id} value={n.code}>{n.label}</option>)}</select></label>}{l2s.length>0&&<label>L2 — Specific issue<select value={l2} onChange={e=>setL2(e.target.value)}><option value="">Select</option>{l2s.map(n=><option key={n.id} value={n.code}>{n.label}</option>)}</select></label>}{fbRequired&&<label>Facebook Page Status<select value={fb} onChange={e=>setFb(e.target.value)}><option value="">Select</option><option>Already existed</option><option>Created on call</option><option>Not created yet</option></select></label>}<label className="wide">Remark{remarkRequired?' *':''}<textarea value={remark} onChange={e=>setRemark(e.target.value)} placeholder="Notes, callback time, complaint, context…"/></label></div><button className="primary" onClick={submit} disabled={saving||!l0||(l1s.length>0&&!l1)||(l2s.length>0&&!l2)||(fbRequired&&!fb)||(remarkRequired&&!remark.trim())}>{saving?'Saving…':'Log Disposition'}</button></section></>}
  </main></div>
}
