'use client';
import { useEffect,useMemo,useState } from 'react';
import { useRouter } from 'next/navigation';
import { PLANS, plansRequiredOn, todayIst } from '@/lib/plans';
import { downloadCsv, type CsvColumn } from '@/lib/csv';
import { multiSort, NO_SORT, type SortState } from '@/lib/sort';
import SortPicker from '@/components/SortPicker';

// CSV of the cases on screen (current bucket, view period, onboarder and search).
const istTime=(v:any)=>v?new Date(v).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'}):'';
// Subscription pill from the Sub Raw fields the daily onboarding sync stores on each case.
// "Cancelled / expired" covers an active subscription the merchant has cancelled as well as a
// subscription that is already cancelled or expired.
type SubPill=''|'active'|'cancelled'|'unknown';
const SUB_PILLS:[Exclude<SubPill,''>,string][]=[['active','Active, not cancelled / expired'],['cancelled','Active but cancelled / expired'],['unknown','Not in Sub Raw']];
const subStatusLabel=(c:any)=>!c.sub_status?'Not in Sub Raw':subPillOf(c)==='active'?'Active, not cancelled':c.sub_status==='ACTIVE'?`Active, cancelled${c.sub_cancelled_at?' on '+String(c.sub_cancelled_at).slice(0,10):''}`:String(c.sub_status).charAt(0)+String(c.sub_status).slice(1).toLowerCase();
const subPillOf=(c:any):SubPill=>!c.sub_status?'unknown':c.sub_status==='ACTIVE'&&!c.sub_cancelled_at?'active':'cancelled';
type CaseSort='credits'|'subscribed'|'stage';
const CASE_SORTS:[CaseSort,string][]=[['stage','Stage reached'],['subscribed','Subscribed date'],['credits','Credits pending']];
// Stages without a set order sort below the ordered ones.
const caseSortValue=(c:any,k:CaseSort):number|null=>k==='credits'?(c.sub_credits??null):k==='subscribed'?(c.sale_date?new Date(String(c.sale_date).slice(0,10)).getTime():null):(c.stage_rank??(c.last_completed_stage?0:null));
const REOPEN_LABEL:any={no_ad_ran:'Reopened: no ad ran',ad_failed:'Reopened: ad failed'};
const ONBOARDING_CSV:CsvColumn<any>[]=[
 ['Cust ID',c=>c.customer_id],['Merchant',c=>c.merchant_name],['Phone',c=>c.phone_number],['Category',c=>[c.category,c.sub_category].filter(Boolean).join(' / ')],
 ['Assigned to',c=>c.assigned_name],['Status',c=>c.current_status==='ads_live'?'Ads Live':c.current_status],['L0',c=>c.current_l0],['L1',c=>c.current_l1],['L2',c=>c.current_l2],
 ['Latest technical issue',c=>c.latest_tech_issue],['Open technical issue',c=>c.has_open_technical?'Yes':'No'],['Language barrier',c=>c.language_barrier_at?'Yes':'No'],
 ['Latest remark',c=>c.latest_remark],['Subscription',c=>c.sub_status?`${c.sub_status}${c.sub_cancelled_at?' (cancelled)':''}`:'Not in Sub Raw'],
 ['Cancelled on',c=>c.sub_cancelled_at],['Credits pending',c=>c.sub_credits],['Plan',c=>c.sub_plan_name],['Plan amount',c=>c.sub_plan_amount],['Subscription expiry',c=>c.sub_expiry_date?String(c.sub_expiry_date).slice(0,10):''],['Last completed stage',c=>c.last_completed_stage],['Reopened',c=>REOPEN_LABEL[c.reopen_reason]||''],['Date of sale',c=>c.sale_date?String(c.sale_date).slice(0,10):''],['Days since sale',c=>c.days_since_sale],
 ['Touches',c=>c.touches],['Last activity',c=>istTime(c.last_activity_at)],['Next callback',c=>istTime(c.next_callback_at)],
 ['Ads live at',c=>istTime(c.ads_live_at)],['Closed at',c=>istTime(c.closed_at)],['Source',c=>c.source_type],
];

type Node={id:string;code:string;label:string;level:number;parent_id:string|null;sort_order:number};
function fmt(v:any){if(!v)return '—';return new Date(v).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',day:'numeric',month:'short',hour:'numeric',minute:'2-digit'});}
function ymd(d:Date){return d.toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});}
function money(v:any){if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(n):null;}

export default function OnboardingConsole(){
 const router=useRouter();
 const [user,setUser]=useState<any>(null),[cases,setCases]=useState<any[]>([]),[nodes,setNodes]=useState<Node[]>([]),[selected,setSelected]=useState<any>(null),[filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const [l0,setL0]=useState(''),[l1,setL1]=useState(''),[l2,setL2]=useState(''),[remark,setRemark]=useState(''),[cbDate,setCbDate]=useState(''),[cbTime,setCbTime]=useState(''),[topUp,setTopUp]=useState(''),[plan,setPlan]=useState(''),[saving,setSaving]=useState(false);
 const [manualCid,setManualCid]=useState(''),[saleDate,setSaleDate]=useState(''),[assignedTo,setAssignedTo]=useState(''),[agents,setAgents]=useState<any[]>([]),[reassigning,setReassigning]=useState(false);
 const [subPill,setSubPill]=useState<SubPill>(''),[stageFilter,setStageFilter]=useState(''),[caseSort,setCaseSort]=useState<SortState<CaseSort>>({...NO_SORT});
 const [viewPeriod,setViewPeriod]=useState<'all'|'today'|'yesterday'|'custom'>('all'),[viewFrom,setViewFrom]=useState(''),[viewTo,setViewTo]=useState(''),[viewAgent,setViewAgent]=useState(''),[viewLoading,setViewLoading]=useState(false);
 const today=ymd(new Date());
 const yesterday=(()=>{const d=new Date();d.setDate(d.getDate()-1);return ymd(d)})();

 async function loadCases(opts?:{from?:string;to?:string;agent?:string}){
   const qs=new URLSearchParams({scope:'all'});
   if(opts?.from&&opts?.to){qs.set('from',opts.from);qs.set('to',opts.to);}
   if(opts?.agent)qs.set('assignedTo',opts.agent);
   const r=await fetch('/api/onboarding/cases?'+qs.toString(),{cache:'no-store'});
   if(r.ok)setCases((await r.json()).cases||[]);
 }
 async function applyView(period=viewPeriod,agent=viewAgent,customFrom=viewFrom,customTo=viewTo){
   setViewLoading(true);setSelected(null);
   if(period==='today')await loadCases({from:today,to:today,agent});
   else if(period==='yesterday')await loadCases({from:yesterday,to:yesterday,agent});
   else if(period==='custom'&&customFrom&&customTo)await loadCases({from:customFrom,to:customTo,agent});
   else await loadCases({agent});
   setViewLoading(false);
 }
 useEffect(()=>{(async()=>{const a=await fetch('/api/auth/access',{cache:'no-store'});if(!a.ok){router.replace('/login');return;}const u=(await a.json()).user;if(!u.isSuperAdmin&&!u.access?.onboarding){router.replace(u.access?.csm?'/csm':'/');return;}setUser(u);const [d]=await Promise.all([fetch('/api/onboarding/dispositions'),loadCases()]);if(d.ok)setNodes((await d.json()).nodes||[]);if(u.isSuperAdmin||u.access?.onboarding==='admin'){const ar=await fetch('/api/admin/access',{cache:'no-store'});if(ar.ok)setAgents(((await ar.json()).agents||[]).filter((x:any)=>x.active&&x.onboarding_access));}setLoading(false);})();},[]);
 const l0s=useMemo(()=>nodes.filter(n=>n.level===0),[nodes]); const l0n=nodes.find(n=>n.code===l0); const l1s=nodes.filter(n=>n.level===1&&n.parent_id===l0n?.id); const l1n=nodes.find(n=>n.code===l1); const l2s=nodes.filter(n=>n.level===2&&n.parent_id===l1n?.id); const callbackRequired=l1==='OB_CALLBACK'; const callbackAvailable=callbackRequired||l1==='OB_TECHNICAL';
 const admin=Boolean(user?.isSuperAdmin||user?.access?.onboarding==='admin'); const customerSuccess=user?.access?.onboarding==='customer_success'; const fullQueue=admin||customerSuccess;
 function bucket(c:any){const cb=c.next_callback_at?new Date(c.next_callback_at):null;const cbDay=cb?ymd(cb):'';if(c.current_status!=='open')return 'completed';if(c.current_status==='open'&&(c.last_activity_at==null||Number(c.touches||0)===0))return 'new';if(cb&&cb.getTime()<Date.now()&&cbDay<=today)return 'overdue';if(cbDay===today)return 'callbacks';return c.current_status==='open'?'all':'completed';}
 function isTechnical(c:any){return Boolean(c.has_open_technical);}
 function isLanguage(c:any){return c.current_status==='open'&&Boolean(c.language_barrier_at);}
 function isReopened(c:any){return c.current_status==='open'&&Boolean(c.reopen_reason);}
 function isAgeing(c:any){return Boolean(c.is_open_as_on)&&Number(c.days_since_sale??0)>=3;}
 const completionRange:[string,string]|null=viewPeriod==='today'?[today,today]:viewPeriod==='yesterday'?[yesterday,yesterday]:viewPeriod==='custom'&&viewFrom&&viewTo?[viewFrom,viewTo]:null;
 function completedInView(c:any){if(c.current_status==='open')return false;if(!completionRange)return true;const completedAt=c.closed_at||c.ads_live_at;if(!completedAt)return false;const completedDay=ymd(new Date(completedAt));return completedDay>=completionRange[0]&&completedDay<=completionRange[1];}
 const openCases=cases.filter(c=>Boolean(c.is_open_as_on));
 const counts={new:cases.filter(c=>bucket(c)==='new').length,callbacks:cases.filter(c=>bucket(c)==='callbacks').length,overdue:cases.filter(c=>bucket(c)==='overdue').length,technical:cases.filter(isTechnical).length,ageing:cases.filter(isAgeing).length,all:openCases.length,completed:cases.filter(completedInView).length,language:cases.filter(isLanguage).length,reopened:cases.filter(isReopened).length};
 const q=search.trim().toLowerCase();
 const bucketRows=cases.filter(c=>filter==='all'?Boolean(c.is_open_as_on):filter==='completed'?completedInView(c):filter==='technical'?isTechnical(c):filter==='language'?isLanguage(c):filter==='reopened'?isReopened(c):filter==='ageing'?isAgeing(c):bucket(c)===filter).filter(c=>!q||String(c.customer_id).includes(q)||String(c.merchant_name||'').toLowerCase().includes(q)||String(c.assigned_name||'').toLowerCase().includes(q)||(q.replace(/\D/g,'').length>=4&&String(c.phone_number||'').replace(/\D/g,'').includes(q.replace(/\D/g,''))));
 // Pills, stage filter and sort apply inside the current bucket; pill counts add up to the bucket.
 const pillCounts:any={active:0,cancelled:0,unknown:0}; for(const c of bucketRows) pillCounts[subPillOf(c)]++;
 const stageOptions=[...new Map(bucketRows.filter(c=>c.last_completed_stage).map(c=>[c.last_completed_stage,c.stage_rank])).entries()].sort((a:any,b:any)=>(a[1]??1e9)-(b[1]??1e9)||String(a[0]).localeCompare(String(b[0]))).map(x=>x[0] as string);
 const filteredRows=bucketRows.filter(c=>(!subPill||subPillOf(c)===subPill)&&(!stageFilter||c.last_completed_stage===stageFilter));
 const shown=multiSort(filteredRows,[caseSort.by&&{value:(c:any)=>caseSortValue(c,caseSort.by as CaseSort),dir:caseSort.dir},caseSort.by&&caseSort.by2&&{value:(c:any)=>caseSortValue(c,caseSort.by2 as CaseSort),dir:caseSort.dir2}].filter(Boolean) as any);
 async function openCase(id:string){setError('');const r=await fetch('/api/onboarding/cases/'+id,{cache:'no-store'});const j=await r.json();if(!r.ok){setError(j.error||'Could not open case');return;}setSelected(j);setL0('');setL1('');setL2('');setRemark('');setCbDate('');setCbTime('');setTopUp('');setPlan('');}
 async function refreshCurrentView(){await applyView(viewPeriod,viewAgent,viewFrom,viewTo);}
 async function save(){if(!selected?.case||!l0)return;const partialTechnicalCallback=l1==='OB_TECHNICAL'&&Boolean(cbDate)!==Boolean(cbTime);if(partialTechnicalCallback){setError('Enter both callback date and time, or leave both blank for a technical issue.');return;}if(l0==='OB_ADDITIONAL_TOPUP'&&(topUp.trim()===''||Number(topUp)<=0)){setError('Enter the additional top-up amount.');return;}setSaving(true);setError('');const id=selected.case.id;const r=await fetch('/api/onboarding/events',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({caseId:id,l0Code:l0,l1Code:l1||null,l2Code:l2||null,remark:remark||null,callbackDate:callbackAvailable&&cbDate?cbDate:null,callbackTime:callbackAvailable&&cbTime?cbTime:null,topUpAmount:topUp.trim()===''?null:topUp,planCode:l0==='OB_SUBS_RENEWED'&&plan?plan:null})});const j=await r.json();setSaving(false);if(!r.ok){setError(j.error||'Could not save');return;}await refreshCurrentView();await openCase(id);}
 async function resolveTech(id:string){const caseId=selected.case.id;const r=await fetch('/api/onboarding/events',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({caseId,resolveTechnicalCaseId:id,remark:'Technical issue resolved'})});if(r.ok){await refreshCurrentView();await openCase(caseId);}else setError((await r.json()).error||'Could not resolve technical issue');}
 async function addCase(){setError('');if(saleDate&&saleDate>today){setError('Date of Sale cannot be in the future.');return;}const r=await fetch('/api/onboarding/cases',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({customerId:manualCid,saleDate:saleDate||null,assignedTo:assignedTo||null})});const j=await r.json();if(!r.ok){setError(j.error||'Could not add case');return;}setManualCid('');setSaleDate('');setAssignedTo('');await refreshCurrentView();await openCase(j.caseId);}
 async function reassign(to:string){if(!selected?.case||!to)return;const caseId=selected.case.id;setReassigning(true);const r=await fetch('/api/onboarding/cases/'+caseId,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({assignedTo:to})});setReassigning(false);if(!r.ok){setError((await r.json()).error||'Could not reassign');return;}await refreshCurrentView();await openCase(caseId);}
 async function logout(){await fetch('/api/auth/logout',{method:'POST'});router.replace('/login');}
 if(loading||!user)return <div className="center">Loading onboarding workspace…</div>;
 const queueAgents=admin?agents:Array.from(new Map(cases.filter((c:any)=>c.assigned_to).map((c:any)=>[c.assigned_to,{id:c.assigned_to,name:c.assigned_name||'Unknown'}])).values());
 return <div className="app-shell"><header><div><strong>Pi Commerce</strong><span> · Onboarding Workspace</span></div><div className="header-actions">{(user.isSuperAdmin||user.access?.seller)&&<a href="/">Seller Workspace</a>}{(user.isSuperAdmin||user.access?.csm)&&<a href="/csm">CSM Workspace</a>}{admin&&<><a href="/analytics?workspace=onboarding">Analytics</a><a href="/admin/access">Manage Access</a></>}<span className="badge">{user.name}</span><button className="linkbtn" onClick={logout}>Logout</button></div></header><main>
  <section className="card"><div className="section-label">My Work Queue</div>{fullQueue&&<div className="range-row" style={{marginBottom:14}}><div className="preset-row" style={{marginBottom:0}}><button onClick={()=>{setViewPeriod('all');applyView('all',viewAgent)}}>All</button><button onClick={()=>{setViewPeriod('today');applyView('today',viewAgent)}}>Today</button><button onClick={()=>{setViewPeriod('yesterday');applyView('yesterday',viewAgent)}}>Yesterday</button></div><label>Onboarder<select value={viewAgent} onChange={e=>{const v=e.target.value;setViewAgent(v);applyView(viewPeriod,v,viewFrom,viewTo)}}><option value="">All onboarders</option>{queueAgents.map((a:any)=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>From<input type="date" value={viewFrom} onChange={e=>{setViewFrom(e.target.value);setViewPeriod('custom')}}/></label><label>To<input type="date" value={viewTo} onChange={e=>{setViewTo(e.target.value);setViewPeriod('custom')}}/></label><button className="primary" disabled={viewLoading||!viewFrom||!viewTo} onClick={()=>applyView('custom',viewAgent,viewFrom,viewTo)}>{viewLoading?'Loading…':'Apply date'}</button></div>}
  <div className="queue-tabs">{[['new','New'],['callbacks','Callbacks Today'],['overdue','Overdue'],['technical','Open Technical'],['ageing','Ageing Open'],['all','All Open'],['completed','Completed']].map(([k,l])=><button key={k} className={filter===k?'active':''} onClick={()=>setFilter(k)}><b>{(counts as any)[k]}</b><span>{l}</span></button>)}</div>{(counts.language>0||counts.reopened>0)&&<div className="lang-chip-row">{counts.language>0&&<button className={filter==='language'?'lang-chip active':'lang-chip'} onClick={()=>setFilter(filter==='language'?'all':'language')}>Language Barrier · {counts.language}</button>}{counts.reopened>0&&<button className={filter==='reopened'?'lang-chip active':'lang-chip'} onClick={()=>setFilter(filter==='reopened'?'all':'reopened')}>Reopened: ad not live / failed · {counts.reopened}</button>}</div>}
  <div className="preset-row csm-sub padtop">{([['','All',bucketRows.length],...SUB_PILLS.filter(([k])=>k!=='unknown'||pillCounts.unknown>0).map(([k,l])=>[k,l,pillCounts[k]])] as [SubPill,string,number][]).map(([k,l,n])=><button key={k||'all'} className={subPill===k?'active':''} onClick={()=>setSubPill(k)}>{l} ({n})</button>)}</div>
  <div className="search-row case-controls"><select value={stageFilter} onChange={e=>setStageFilter(e.target.value)}><option value="">All stages</option>{stageOptions.map(st=><option key={st} value={st}>{st}</option>)}</select><SortPicker options={CASE_SORTS} value={caseSort} onChange={setCaseSort} dateKeys={['subscribed']}/></div><div className="search-row padtop"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search merchant, customer ID, phone or onboarder"/></div></section>
  {admin&&<section className="card"><div className="section-label">Add Onboarding Case</div><div className="form-grid"><label>Customer ID<input value={manualCid} onChange={e=>setManualCid(e.target.value)}/></label><label>Date of Sale<input type="date" max={today} value={saleDate} onChange={e=>setSaleDate(e.target.value)}/></label><label>Assign to<select value={assignedTo} onChange={e=>{const v=e.target.value;setAssignedTo(v)}}><option value="">Auto assign by workload</option>{agents.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label></div><button className="primary" disabled={!/^\d+$/.test(manualCid)} onClick={addCase}>Add Case</button></section>}
  {error&&<div className="error card">{error}</div>}
  <div className="onboarding-grid"><section className="card"><div className="leads-head"><div className="section-label">{filter==='all'?'All Open Cases':filter==='completed'?'Completed Cases':filter==='language'?'Language Barrier (open)':filter==='reopened'?'Reopened: ad not live / failed':filter.replace(/(^|\s)\S/g,s=>s.toUpperCase())}</div>{admin&&<button className="csv-btn" onClick={()=>downloadCsv(`onboarding-${filter}-${today}.csv`,ONBOARDING_CSV,shown)}>Download CSV</button>}</div>{shown.length===0?<div className="empty">No cases in this bucket.</div>:<div className="case-list">{shown.map(c=><button key={c.id} onClick={()=>openCase(c.id)} className={selected?.case?.id===c.id?'selected':''}><div><strong>{c.merchant_name||`Customer ${c.customer_id}`}</strong><span>Cust ID {c.customer_id} · {c.assigned_name||'Unassigned'}</span>{c.current_status!=='open'&&<span>Completed {fmt(c.closed_at||c.ads_live_at)}</span>}</div><div className="case-tags"><em>{c.days_since_sale}d since sale</em><em>{c.last_activity_at?`${c.days_since_last_activity}d since touch`:'New'}</em>{c.next_callback_at&&<em>Callback {fmt(c.next_callback_at)}</em>}{c.has_open_technical&&<em>Technical</em>}{c.reopen_reason&&c.current_status==='open'&&<em className="tag-warn">{REOPEN_LABEL[c.reopen_reason]}</em>}{c.sub_status&&subPillOf(c)==='cancelled'&&<em className="tag-warn">{c.sub_status==='ACTIVE'?'Sub active, cancelled':'Sub '+String(c.sub_status).toLowerCase()}</em>}{c.sub_credits!=null&&<em>Credits ₹{Math.round(c.sub_credits).toLocaleString('en-IN')}</em>}{c.last_completed_stage&&<em>Stage: {c.last_completed_stage}</em>}{c.current_status!=='open'&&<em>{c.current_status==='ads_live'?'Ads Live':c.current_status}</em>}</div></button>)}</div>}</section>
   <section className="card case-detail"><div className="section-label">Case</div>{!selected?<div className="empty">Open a case to see merchant context and history.</div>:<CaseDetail data={selected} l0={l0} setL0={(v:string)=>{setL0(v);setL1('');setL2('');setCbDate('');setCbTime('');setTopUp('');setPlan('')}} l1={l1} setL1={(v:string)=>{setL1(v);setL2('');setCbDate('');setCbTime('')}} l2={l2} setL2={setL2} remark={remark} setRemark={setRemark} cbDate={cbDate} setCbDate={setCbDate} cbTime={cbTime} setCbTime={setCbTime} topUp={topUp} setTopUp={setTopUp} plan={plan} setPlan={setPlan} callbackRequired={callbackRequired} callbackAvailable={callbackAvailable} l0s={l0s} l1s={l1s} l2s={l2s} save={save} saving={saving} resolveTech={resolveTech} admin={admin} customerSuccess={customerSuccess} agents={agents} reassign={reassign} reassigning={reassigning}/>}</section>
  </div>
 </main></div>;
}

function CaseDetail(p:any){const c=p.data.case;const additionalTopUp=p.l0==='OB_ADDITIONAL_TOPUP';const planRequired=p.l0==='OB_SUBS_RENEWED'&&plansRequiredOn(todayIst());const canLog=c.current_status==='open'||c.current_status==='ads_live';const postLiveCodes=new Set(['OB_ANOTHER_AD_LIVE','OB_CREATIVE_UPDATED']);const l0Options=c.current_status==='ads_live'?p.l0s.filter((n:any)=>n.code==='OB_ADDITIONAL_TOPUP'):p.l0s.filter((n:any)=>n.code!=='OB_ADDITIONAL_TOPUP'&&!postLiveCodes.has(n.code));return <><div className="summary-grid"><div><span>Merchant</span><b>{c.merchant_name||'—'}</b></div><div><span>Customer ID</span><b>{c.customer_id}</b></div><div><span>Phone</span><b>{c.phone_number||'—'}</b></div><div><span>Assigned to</span><b>{c.assigned_name||'—'}</b></div><div><span>Date of sale</span><b>{c.sale_date?String(c.sale_date).slice(0,10):'—'}</b></div><div><span>Current status</span><b>{[c.current_l0,c.current_l1,c.current_l2].filter(Boolean).join(' → ')||'New'}</b></div><div><span>Subscription plan</span><b>{c.sub_plan_name?`${c.sub_plan_name}${c.sub_plan_amount!=null?` · ₹${Math.round(Number(c.sub_plan_amount)).toLocaleString('en-IN')}`:''}`:'—'}</b></div><div><span>Credits</span><b>{c.sub_credits!=null?`₹${Math.round(Number(c.sub_credits)).toLocaleString('en-IN')}`:'—'}</b></div><div><span>Subscription status</span><b>{subStatusLabel(c)}</b></div><div><span>Subscription expiry</span><b>{c.sub_expiry_date?String(c.sub_expiry_date).slice(0,10):'—'}</b></div></div>
 {p.admin&&<div className="form-grid padtop"><label>Reassign case<select value={c.assigned_to||''} disabled={p.reassigning} onChange={(e:any)=>p.reassign(e.target.value)}><option value="">Select onboarder</option>{p.agents.map((a:any)=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label></div>}
 <div className="section-label subhead">History</div><div className="timeline">{p.data.events.length===0?<div className="empty">No calls/updates yet.</div>:p.data.events.map((e:any)=><div className="event" key={e.id}><div className="event-top"><b>{fmt(e.event_time)} · {e.agent_name||e.agent_name_raw||'System'}</b><span className="status">{[e.l0_label_snapshot,e.l1_label_snapshot,e.l2_label_snapshot].filter(Boolean).join(' → ')||'Update'}</span></div>{e.callback_at&&<div className="callback-history">Callback: <b>{fmt(e.callback_at)}</b></div>}{e.top_up_amount_inr!=null&&<div className="callback-history">Top-up done: <b>{money(e.top_up_amount_inr)}</b></div>}<div className={e.remark?'remark':'remark muted'}>{e.remark||'No remark logged'}</div></div>)}</div>
 {p.data.technicalCases.length>0&&<><div className="section-label subhead">Technical Cases</div>{p.data.technicalCases.map((t:any)=><div className="tech-row" key={t.id}><div><b>{t.issue_label}</b><span>{t.status==='open'?'Open':'Resolved'} · Opened {fmt(t.opened_at)} · {t.latest_remark||'No remark'}</span></div>{t.status==='open'&&(c.current_status==='open'||p.customerSuccess)&&<button onClick={()=>p.resolveTech(t.id)}>Mark Resolved</button>}</div>)}</>}
 {canLog&&<><div className="section-label subhead">{c.current_status==='ads_live'?'Log Additional Top-up':'Log New Update'}</div><div className="form-grid"><label>L0<select value={p.l0} onChange={(e:any)=>p.setL0(e.target.value)}><option value="">Select outcome</option>{l0Options.map((n:any)=><option key={n.id} value={n.code}>{n.label}</option>)}</select></label>{!additionalTopUp&&p.l1s.length>0&&<label>L1<select value={p.l1} onChange={(e:any)=>p.setL1(e.target.value)}><option value="">Select reason</option>{p.l1s.map((n:any)=><option key={n.id} value={n.code}>{n.label}</option>)}</select></label>}{!additionalTopUp&&p.l2s.length>0&&<label>L2<select value={p.l2} onChange={(e:any)=>p.setL2(e.target.value)}><option value="">Select issue</option>{p.l2s.map((n:any)=><option key={n.id} value={n.code}>{n.label}</option>)}</select></label>}{!additionalTopUp&&p.callbackAvailable&&<><label>Callback Date{p.callbackRequired?' *':' (optional)'}<input type="date" value={p.cbDate} onChange={(e:any)=>p.setCbDate(e.target.value)}/></label><label>Callback Time{p.callbackRequired?' *':' (optional)'}<input type="time" value={p.cbTime} onChange={(e:any)=>p.setCbTime(e.target.value)}/></label></>}{planRequired&&<label>Plan Renewed *<select value={p.plan} onChange={(e:any)=>p.setPlan(e.target.value)}><option value="">Select plan</option>{Object.entries(PLANS).map(([code,pl])=><option key={code} value={code}>{pl.label} · ₹{pl.price.toLocaleString('en-IN')} + GST</option>)}</select></label>}<label>Top-up Done Amount (₹){additionalTopUp?' *':''}<input type="number" min="0" step="0.01" value={p.topUp} onChange={(e:any)=>p.setTopUp(e.target.value)} placeholder={additionalTopUp?'Required':'Optional'}/></label>{!additionalTopUp&&<label className="wide">Remark<textarea value={p.remark} onChange={(e:any)=>p.setRemark(e.target.value)} placeholder="What happened / next action"/></label>}</div><button className="primary" onClick={p.save} disabled={p.saving||!p.l0||(p.l1s.length>0&&!p.l1&&!additionalTopUp)||(p.l2s.length>0&&!p.l2&&!additionalTopUp)||(p.callbackRequired&&(!p.cbDate||!p.cbTime)&&!additionalTopUp)||(additionalTopUp&&(p.topUp.trim()===''||Number(p.topUp)<=0))||(planRequired&&!p.plan)}>{p.saving?'Saving…':additionalTopUp?'Log Top-up':'Log Update'}</button></>}
 </>}