'use client';
import { useEffect,useMemo,useState } from 'react';
import { useRouter } from 'next/navigation';

type Node={id:string;code:string;label:string;level:number;parent_id:string|null;sort_order:number};
function fmt(v:any){if(!v)return '—';return new Date(v).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',day:'numeric',month:'short',hour:'numeric',minute:'2-digit'});}
function ymd(d:Date){return d.toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});}
function money(v:any){if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(n):null;}

export default function OnboardingConsole(){
 const router=useRouter();
 const [user,setUser]=useState<any>(null),[cases,setCases]=useState<any[]>([]),[nodes,setNodes]=useState<Node[]>([]),[selected,setSelected]=useState<any>(null),[filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const [l0,setL0]=useState(''),[l1,setL1]=useState(''),[l2,setL2]=useState(''),[remark,setRemark]=useState(''),[cbDate,setCbDate]=useState(''),[cbTime,setCbTime]=useState(''),[topUp,setTopUp]=useState(''),[saving,setSaving]=useState(false);
 const [manualCid,setManualCid]=useState(''),[saleDate,setSaleDate]=useState(''),[assignedTo,setAssignedTo]=useState(''),[agents,setAgents]=useState<any[]>([]),[reassigning,setReassigning]=useState(false);
 const [snapshot,setSnapshot]=useState<any>(null),[snapshotFrom,setSnapshotFrom]=useState(''),[snapshotTo,setSnapshotTo]=useState(''),[snapshotLoading,setSnapshotLoading]=useState(false);
 async function loadCases(){const r=await fetch('/api/onboarding/cases?scope=all',{cache:'no-store'});if(r.ok)setCases((await r.json()).cases||[]);}
 async function loadSnapshot(from:string,to:string){setSnapshotLoading(true);setSnapshotFrom(from);setSnapshotTo(to);const r=await fetch(`/api/onboarding/analytics?from=${from}&to=${to}`,{cache:'no-store'});if(r.ok)setSnapshot(await r.json());setSnapshotLoading(false);}
 useEffect(()=>{(async()=>{const a=await fetch('/api/auth/access',{cache:'no-store'});if(!a.ok){router.replace('/login');return;}const u=(await a.json()).user;if(!u.isSuperAdmin&&!u.access?.onboarding){router.replace('/');return;}setUser(u);const [d]=await Promise.all([fetch('/api/onboarding/dispositions'),loadCases()]);if(d.ok)setNodes((await d.json()).nodes||[]);if(u.isSuperAdmin||u.access?.onboarding==='admin'){const ar=await fetch('/api/admin/access',{cache:'no-store'});if(ar.ok)setAgents(((await ar.json()).agents||[]).filter((x:any)=>x.active&&x.onboarding_access));const t=ymd(new Date());await loadSnapshot(t,t);}setLoading(false);})();},[]);
 const l0s=useMemo(()=>nodes.filter(n=>n.level===0),[nodes]); const l0n=nodes.find(n=>n.code===l0); const l1s=nodes.filter(n=>n.level===1&&n.parent_id===l0n?.id); const l1n=nodes.find(n=>n.code===l1); const l2s=nodes.filter(n=>n.level===2&&n.parent_id===l1n?.id); const callbackRequired=l1==='OB_CALLBACK'; const callbackAvailable=callbackRequired||l1==='OB_TECHNICAL';
 const today=ymd(new Date());
 function bucket(c:any){if(c.current_status!=='open')return 'completed';const cb=c.next_callback_at?new Date(c.next_callback_at):null;const cbDay=cb?ymd(cb):'';if(c.last_activity_at==null||Number(c.touches||0)===0)return 'new';if(cb&&cb.getTime()<Date.now()&&cbDay<=today)return 'overdue';if(cbDay===today)return 'callbacks';if(c.has_open_technical)return 'technical';if(Number(c.days_since_last_activity??0)>=3||Number(c.days_since_sale??0)>=7)return 'ageing';return 'all';}
 const openCases=cases.filter(c=>c.current_status==='open');
 const counts={new:cases.filter(c=>bucket(c)==='new').length,callbacks:cases.filter(c=>bucket(c)==='callbacks').length,overdue:cases.filter(c=>bucket(c)==='overdue').length,technical:cases.filter(c=>bucket(c)==='technical').length,ageing:cases.filter(c=>bucket(c)==='ageing').length,all:openCases.length,completed:cases.filter(c=>c.current_status!=='open').length};
 const q=search.trim().toLowerCase();
 const shown=cases.filter(c=>filter==='all'?c.current_status==='open':bucket(c)===filter).filter(c=>!q||String(c.customer_id).includes(q)||String(c.merchant_name||'').toLowerCase().includes(q)||String(c.assigned_name||'').toLowerCase().includes(q));
 async function openCase(id:string){setError('');const r=await fetch('/api/onboarding/cases/'+id,{cache:'no-store'});const j=await r.json();if(!r.ok){setError(j.error||'Could not open case');return;}setSelected(j);setL0('');setL1('');setL2('');setRemark('');setCbDate('');setCbTime('');setTopUp('');}
 async function save(){if(!selected?.case||!l0)return;const partialTechnicalCallback=l1==='OB_TECHNICAL'&&Boolean(cbDate)!==Boolean(cbTime);if(partialTechnicalCallback){setError('Enter both callback date and time, or leave both blank for a technical issue.');return;}setSaving(true);setError('');const r=await fetch('/api/onboarding/events',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({caseId:selected.case.id,l0Code:l0,l1Code:l1||null,l2Code:l2||null,remark:remark||null,callbackDate:callbackAvailable&&cbDate?cbDate:null,callbackTime:callbackAvailable&&cbTime?cbTime:null,topUpAmount:topUp.trim()===''?null:topUp})});const j=await r.json();setSaving(false);if(!r.ok){setError(j.error||'Could not save');return;}await Promise.all([loadCases(),openCase(selected.case.id)]);if(user?.isSuperAdmin||user?.access?.onboarding==='admin')await loadSnapshot(snapshotFrom||today,snapshotTo||today);}
 async function resolveTech(id:string){const r=await fetch('/api/onboarding/events',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({caseId:selected.case.id,resolveTechnicalCaseId:id,remark:'Technical issue resolved'})});if(r.ok){await Promise.all([loadCases(),openCase(selected.case.id)]);if(user?.isSuperAdmin||user?.access?.onboarding==='admin')await loadSnapshot(snapshotFrom||today,snapshotTo||today);}else setError((await r.json()).error||'Could not resolve technical issue');}
 async function addCase(){setError('');if(saleDate&&saleDate>today){setError('Date of Sale cannot be in the future.');return;}const r=await fetch('/api/onboarding/cases',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({customerId:manualCid,saleDate:saleDate||null,assignedTo:assignedTo||null})});const j=await r.json();if(!r.ok){setError(j.error||'Could not add case');return;}setManualCid('');setSaleDate('');setAssignedTo('');await loadCases();await openCase(j.caseId);await loadSnapshot(snapshotFrom||today,snapshotTo||today);}
 async function reassign(to:string){if(!selected?.case||!to)return;setReassigning(true);const r=await fetch('/api/onboarding/cases/'+selected.case.id,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({assignedTo:to})});setReassigning(false);if(!r.ok){setError((await r.json()).error||'Could not reassign');return;}await Promise.all([loadCases(),openCase(selected.case.id)]);await loadSnapshot(snapshotFrom||today,snapshotTo||today);}
 async function logout(){await fetch('/api/auth/logout',{method:'POST'});router.replace('/login');}
 if(loading||!user)return <div className="center">Loading onboarding workspace…</div>;
 const admin=user.isSuperAdmin||user.access?.onboarding==='admin';
 const yesterday=(()=>{const d=new Date();d.setDate(d.getDate()-1);return ymd(d)})();
 return <div className="app-shell"><header><div><strong>Pi Commerce</strong><span> · Onboarding Workspace</span></div><div className="header-actions">{(user.isSuperAdmin||user.access?.seller)&&<a href="/">Seller Workspace</a>}{admin&&<><a href="/analytics?workspace=onboarding">Analytics</a><a href="/admin/access">Manage Access</a></>}<span className="badge">{user.name}</span><button className="linkbtn" onClick={logout}>Logout</button></div></header><main>
  <section className="card"><div className="section-label">My Work Queue</div><div className="queue-tabs">{[['new','New'],['callbacks','Callbacks Today'],['overdue','Overdue'],['technical','Open Technical'],['ageing','Ageing / Stuck'],['all','All Open'],['completed','Completed']].map(([k,l])=><button key={k} className={filter===k?'active':''} onClick={()=>setFilter(k)}><b>{(counts as any)[k]}</b><span>{l}</span></button>)}</div><div className="search-row padtop"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search merchant, customer ID or onboarder"/></div></section>
  {admin&&<section className="card"><div className="section-label">Team Snapshot</div><div className="preset-row"><button onClick={()=>loadSnapshot(today,today)}>Today</button><button onClick={()=>loadSnapshot(yesterday,yesterday)}>Yesterday</button></div><div className="range-row"><label>From<input type="date" value={snapshotFrom} onChange={e=>setSnapshotFrom(e.target.value)}/></label><label>To<input type="date" value={snapshotTo} onChange={e=>setSnapshotTo(e.target.value)}/></label><button className="primary" disabled={snapshotLoading||!snapshotFrom||!snapshotTo} onClick={()=>loadSnapshot(snapshotFrom,snapshotTo)}>{snapshotLoading?'Loading…':'Apply'}</button></div>{snapshot&&<><div className="kpis onboarding-workspace-kpis"><div><b>{snapshot.cases_received}</b><span>Cases Received</span></div><div><b>{snapshot.touches}</b><span>Touches</span></div><div><b>{snapshot.ads_live}</b><span>Ads Live</span></div><div><b>{snapshot.subscriptions_renewed}</b><span>Subs Renewed</span></div><div><b>{money(snapshot.top_up_amount)||'₹0'}</b><span>Top-up Done</span></div><div><b>{snapshot.technical_resolved}</b><span>Tech Resolved</span></div></div><div className="section-label subhead">Individual Performance</div><table className="split"><thead><tr><th>Onboarder</th><th>Assigned</th><th>Touches</th><th>Ads Live</th><th>Subs Renewed</th><th>Top-up</th><th>Tech Open</th><th>Tech Resolved</th></tr></thead><tbody>{(snapshot.agentPerformance||[]).map((r:any)=><tr key={r.id}><td>{r.name}</td><td>{r.assigned}</td><td>{r.touches}</td><td>{r.ads_live}</td><td>{r.subscriptions_renewed}</td><td>{money(r.top_up_amount)||'₹0'}</td><td>{r.tech_open}</td><td>{r.tech_resolved}</td></tr>)}</tbody></table></>}</section>}
  {admin&&<section className="card"><div className="section-label">Add Onboarding Case</div><div className="form-grid"><label>Customer ID<input value={manualCid} onChange={e=>setManualCid(e.target.value)}/></label><label>Date of Sale<input type="date" max={today} value={saleDate} onChange={e=>setSaleDate(e.target.value)}/></label><label>Assign to<select value={assignedTo} onChange={e=>setAssignedTo(e.target.value)}><option value="">Auto assign by workload</option>{agents.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label></div><button className="primary" disabled={!/^\d+$/.test(manualCid)} onClick={addCase}>Add Case</button></section>}
  {error&&<div className="error card">{error}</div>}
  <div className="onboarding-grid"><section className="card"><div className="section-label">{filter==='all'?'All Open Cases':filter==='completed'?'Completed Cases':filter.replace(/(^|\s)\S/g,s=>s.toUpperCase())}</div>{shown.length===0?<div className="empty">No cases in this bucket.</div>:<div className="case-list">{shown.map(c=><button key={c.id} onClick={()=>openCase(c.id)} className={selected?.case?.id===c.id?'selected':''}><div><strong>{c.merchant_name||`Customer ${c.customer_id}`}</strong><span>Cust ID {c.customer_id} · {c.assigned_name||'Unassigned'}</span>{c.current_status!=='open'&&<span>Completed {fmt(c.closed_at||c.ads_live_at)}</span>}</div><div className="case-tags"><em>{c.days_since_sale}d since sale</em><em>{c.last_activity_at?`${c.days_since_last_activity}d since touch`:'New'}</em>{c.next_callback_at&&<em>Callback {fmt(c.next_callback_at)}</em>}{c.has_open_technical&&<em>Technical</em>}{c.current_status!=='open'&&<em>{c.current_status==='ads_live'?'Ads Live':c.current_status}</em>}</div></button>)}</div>}</section>
   <section className="card case-detail"><div className="section-label">Case</div>{!selected?<div className="empty">Open a case to see merchant context and history.</div>:<CaseDetail data={selected} l0={l0} setL0={(v:string)=>{setL0(v);setL1('');setL2('');setCbDate('');setCbTime('')}} l1={l1} setL1={(v:string)=>{setL1(v);setL2('');setCbDate('');setCbTime('')}} l2={l2} setL2={setL2} remark={remark} setRemark={setRemark} cbDate={cbDate} setCbDate={setCbDate} cbTime={cbTime} setCbTime={setCbTime} topUp={topUp} setTopUp={setTopUp} callbackRequired={callbackRequired} callbackAvailable={callbackAvailable} l0s={l0s} l1s={l1s} l2s={l2s} save={save} saving={saving} resolveTech={resolveTech} admin={admin} agents={agents} reassign={reassign} reassigning={reassigning}/>}</section>
  </div>
 </main></div>;
}

function CaseDetail(p:any){const c=p.data.case;return <><div className="summary-grid"><div><span>Merchant</span><b>{c.merchant_name||'—'}</b></div><div><span>Customer ID</span><b>{c.customer_id}</b></div><div><span>Phone</span><b>{c.phone_number||'—'}</b></div><div><span>Assigned to</span><b>{c.assigned_name||'—'}</b></div><div><span>Date of sale</span><b>{c.sale_date?String(c.sale_date).slice(0,10):'—'}</b></div><div><span>Current status</span><b>{[c.current_l0,c.current_l1,c.current_l2].filter(Boolean).join(' → ')||'New'}</b></div></div>
 {p.admin&&<div className="form-grid padtop"><label>Reassign case<select value={c.assigned_to||''} disabled={p.reassigning} onChange={(e:any)=>p.reassign(e.target.value)}><option value="">Select onboarder</option>{p.agents.map((a:any)=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label></div>}
 <div className="section-label subhead">History</div><div className="timeline">{p.data.events.length===0?<div className="empty">No calls/updates yet.</div>:p.data.events.map((e:any)=><div className="event" key={e.id}><div className="event-top"><b>{fmt(e.event_time)} · {e.agent_name||e.agent_name_raw||'System'}</b><span className="status">{[e.l0_label_snapshot,e.l1_label_snapshot,e.l2_label_snapshot].filter(Boolean).join(' → ')||'Update'}</span></div>{e.callback_at&&<div className="callback-history">Callback: <b>{fmt(e.callback_at)}</b></div>}{e.top_up_amount_inr!=null&&<div className="callback-history">Top-up done: <b>{money(e.top_up_amount_inr)}</b></div>}<div className={e.remark?'remark':'remark muted'}>{e.remark||'No remark logged'}</div></div>)}</div>
 {p.data.technicalCases.length>0&&<><div className="section-label subhead">Technical Cases</div>{p.data.technicalCases.map((t:any)=><div className="tech-row" key={t.id}><div><b>{t.issue_label}</b><span>{t.status==='open'?'Open':'Resolved'} · Opened {fmt(t.opened_at)} · {t.latest_remark||'No remark'}</span></div>{t.status==='open'&&c.current_status==='open'&&<button onClick={()=>p.resolveTech(t.id)}>Mark Resolved</button>}</div>)}</>}
 {c.current_status==='open'&&<><div className="section-label subhead">Log New Update</div><div className="form-grid"><label>L0<select value={p.l0} onChange={(e:any)=>p.setL0(e.target.value)}><option value="">Select outcome</option>{p.l0s.map((n:any)=><option key={n.id} value={n.code}>{n.label}</option>)}</select></label>{p.l1s.length>0&&<label>L1<select value={p.l1} onChange={(e:any)=>p.setL1(e.target.value)}><option value="">Select reason</option>{p.l1s.map((n:any)=><option key={n.id} value={n.code}>{n.label}</option>)}</select></label>}{p.l2s.length>0&&<label>L2<select value={p.l2} onChange={(e:any)=>p.setL2(e.target.value)}><option value="">Select issue</option>{p.l2s.map((n:any)=><option key={n.id} value={n.code}>{n.label}</option>)}</select></label>}{p.callbackAvailable&&<><label>Callback Date{p.callbackRequired?' *':' (optional)'}<input type="date" value={p.cbDate} onChange={(e:any)=>p.setCbDate(e.target.value)}/></label><label>Callback Time{p.callbackRequired?' *':' (optional)'}<input type="time" value={p.cbTime} onChange={(e:any)=>p.setCbTime(e.target.value)}/></label></>}<label>Top-up Done Amount (₹)<input type="number" min="0" step="0.01" value={p.topUp} onChange={(e:any)=>p.setTopUp(e.target.value)} placeholder="Optional"/></label><label className="wide">Remark<textarea value={p.remark} onChange={(e:any)=>p.setRemark(e.target.value)} placeholder="What happened / next action"/></label></div><button className="primary" onClick={p.save} disabled={p.saving||!p.l0||(p.l1s.length>0&&!p.l1)||(p.l2s.length>0&&!p.l2)||(p.callbackRequired&&(!p.cbDate||!p.cbTime))}>{p.saving?'Saving…':'Log Update'}</button></>}
 </>}
